layout:
  dim:
  - label: 'cmd'
    size: 12
    stride: 0
  data_offset: 0
data:
  - 0 # "left_back_hip"
  - 0 # "left_back_knee"
  - 0 # "left_back_yaw"
  - 0 # "left_front_hip"
  - -0.78 # "left_front_knee"
  - 0 # "left_front_yaw"
  - 0 # "right_back_hip"
  - 0 # "right_back_knee"
  - 0 # "right_back_yaw"
  - 0 # "right_front_hip"
  - 0 # "right_front_knee"
  - 0 # "right_front_yaw"

# Open termial, and run:
# rostopic pub --once /jnt_group_controller/command std_msgs/Float64MultiArray -f ~/qr_ws/src/qr_ws/qr_control/config/cmd.yaml