jnt_group_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - "left_back_hip"
    - "left_back_knee"
    - "left_back_yaw"
    - "left_front_hip"
    - "left_front_knee"
    - "left_front_yaw"
    - "right_back_hip"
    - "right_back_knee"
    - "right_back_yaw"
    - "right_front_hip"
    - "right_front_knee"
    - "right_front_yaw"