jnt_num_of_leg: 3
leg_num: 4

joint_0: "left_back_yaw"
joint_1: "left_back_hip"
joint_2: "left_back_knee"
root_0:  "body"
tip_0:   "left_back_foot"

joint_3: "left_front_yaw"
joint_4: "left_front_hip"
joint_5: "left_front_knee"
root_1:  "body"
tip_1:   "left_front_foot"

joint_6: "right_back_yaw"
joint_7: "right_back_hip"
joint_8: "right_back_knee"
root_2:  "body"
tip_2:   "right_back_foot"

joint_9: "right_front_yaw"
joint_10:  "right_front_hip"
joint_11: "right_front_knee"
root_3:  "body"
tip_3:   "right_front_foot"